irctcUsername=
irctcPassword=
fromStationCode=SHC
toStationCode=PNBE
journeyDate=20/03/2024
quota=TATKAL
trainNumber=12567
trainClass=CC
passengerCount=2
passenger1=Abhishek Kumar|45|M
passenger2=Roshan Kumar|60|F
upiVPA=