irctcUsername=
irctcPassword=
fromStationCode=DNR
toStationCode=SMVB
journeyDate=23/03/2024
quota=TATKAL
trainNumber=12296
trainClass=2A
passengerCount=2
passenger1=Abhishek Kumar|25|M|SL
passenger2=Isha Kumari|20|F|SU
upiId=